### ISSUE TITLE
Обязательность наложения ЭЦП на заполняемую форму услуги и доп.информирование

### ISSUE THREAD

**Issue by bvv4ik** [e-government-ua/i#1022]
- [x] 1. Если в поле с id="form_signed" стоит required="true", то - автоматически включать чекбокс (возле сабмита) и скрывать его.

- [x] 2. При включенном чекбоксе. отображать перед кнопкой сабмита надпись:
"Після натискання "Замовити послугу" вас буде перенаправлено на сторінку підпису вашої заявки електронно-цифровим підписом"

**Comment by nazarenkod** [comment]
подскажите как проверить

**Comment by NizhnikAlex** [comment]
Сейчас отключил услугу, которая это использует - отменена с 1.01.2016. Когда переберем все услуги, подключу для теста

**Comment by nazarenkod** [comment]
дайте знать как подключите:)

**Comment by GrekD** [comment]
@nazarenkod 
1 dnepr_cnap_219.bpmn
откорректировала этот процесс чтоб можно было протестирвоать. Единственное, что я изменила - это добавила required="true" для form_signed  поля, запушила, запускаю услугу - вылазит ошибка 

[$parse:lexerr] Lexer Error: Unexpected next character at columns 16-16 [с] in expression [formData.params.сhanged.value]. http://errors.angularjs.org/1.3.15/$parse/lexerr?p0=Unexpected%20next%20character%20&p1=s%2016-16%20%5B%D1%81%5D&p2=formData.params.%D1%81hanged.value (caused by "<dropdown-organ ng-switch-when="select" ng-if="property.id==='sID_Public_SubjectOrganJoin'" ng-model="data.formData.params[property.id].value" form-data-property="data.formData.params[property.id]" service-data="oServiceData" activiti-form="activitiForm" ng-required="isFieldRequired(property)" form-data="data.formData" class="ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope">")

2. по второму пункту работает - фраза отображается

тестировать можно на процессе 
https://test.igov.org.ua/service/1411/general
Винницкая область, Теплик
логін-пароль для дашборда чиновника (https://test.region.igov.org.ua/): teplikcnap

**Comment by Sokhatsky** [comment]
При спробі зайти в послугу https://test.igov.org.ua/service/1411/general
Винницкая область, Теплик з'являється повідомлення про помилку
![pic 1022](https://cloud.githubusercontent.com/assets/16464887/12379827/e7f25af2-bd6a-11e5-914f-fb23777fe612.png)

**Comment by GrekD** [comment]
доработка работает

**Comment by Sokhatsky** [comment]
Для услуги https://test.igov.org.ua/service/1411/general 
обл. Вінницька, м. Теплик
При первой попытке выбрать город выскакивает сообщение об ошибке
![2016-03-07-_2237](https://cloud.githubusercontent.com/assets/16464887/13583500/57d2b382-e4ba-11e5-93d9-95665591b069.png)
При заполнении полей данной услуги для поля "Оберіть свій район або місто" отсутствует возможность выбора кроме ввода с клавиатуры
![2016-03-07_2238](https://cloud.githubusercontent.com/assets/16464887/13583635/2bf556ba-e4bb-11e5-8275-08b64a3e0b6a.png)
Для поля "Найменування громадського об'єднання" присутсвует пустая строка 
![2016-03-07_2239](https://cloud.githubusercontent.com/assets/16464887/13584361/e25d15d4-e4be-11e5-9f74-67f3df9d3ef3.png)
В низу формы услуги присутствует большой отступ между строками
![2016-03-07_2252](https://cloud.githubusercontent.com/assets/16464887/13584436/4a700f3c-e4bf-11e5-9ec3-20f7eb40e8d8.png)
После нажатие на кнопку "Замовити послугу" появляется сообщение об ошибке
![2016-03-07_2304](https://cloud.githubusercontent.com/assets/16464887/13584491/86464c24-e4bf-11e5-81d2-0a54a6833d7a.png)
