### ISSUE TITLE
Questions from Canada

### ISSUE THREAD

**Issue by Vanuan** [e-government-ua/i#708]
Hi guys, thanks for the work you've been doing.

Please welcome Stephen Russett, who is working for Canadian government.
He has some questions to ask.

@StephenOTT, go ahead.

**Comment by StephenOTT** [comment]
HI!

I do a lot of work with various governments across canada.  I used to work in government, then moved to private sector working as a contractor on various projects building online services/eservices and government websites and apps.

I have been working on some government services strategies, and @Vanuan and I had some conversations about system designs for building government service portals / platforms.

Would you be able to share some of your lessons learned?  Why did you select activity rather than another BPM (such as ProcessMaker, or Camunda)?  If you had to do it over again, would you do anything differently?  What were your challenges, roadblocks, problems you did not anticipate, etc

Thanks!

**Comment by valdemar8080** [comment]
Hi guys!!

Mr. Vladimir Belyavtsev manages the development team. So I hope he would help you with your questions. His login on github 'bvv4ik' or skype 'belyavtsevw'.

I heard they have chosen Activiti because of its good practice of implementation in the biggest bank of Ukraine - Privatbank. The usage of Activiti had reduced new bank's services launch time from several months to several weeks and let to eleminate a lot of programmer's routine. The core of development team for igov.org.ua came from Privatbank so they brought this BPM as well.

Best Regards,
Vadym Rudniev

**Comment by valdemar8080** [comment]
@Vanuan @StephenOTT -see comment above

**Comment by StephenOTT** [comment]
Thank you!!






On Sun, Aug 30, 2015 at 9:19 AM -0700, "Vadym Rudniev" <notifications@github.com> wrote:












@Vanuan @StephenOTT -see comment above

**Comment by valdemar8080** [comment]
Hi @Vanuan, @StephenOTT !

I've just contacted to Vladimir Belyavtsev and here are the answers by him.
Q. Why did you select activity rather than another BPM (such as ProcessMaker, or Camunda)?
A. There is a positive experience of using it under a heavy load. 
(my remark - I think Vladimir ment www.privat24.ua on-line banking service with 10+ million subscribers.)
Q. If you had to do it over again, would you do anything differently?
A. We would keep things just the same.
Q. What were your challenges, roadblocks, problems you did not anticipate, etc ?
A. There were some conficts if you wanted to rename BP files which had been alredy deployed. In this case you should also rename ID otherwise error occurs during re-deploy.

Best Regards,
Vadym Rudniev

**Comment by StephenOTT** [comment]
@valdemar8080 @Vanuan Thanks for the info!  Great stuff.

We were actually able to get startup funding for this type of project.  Check out DigitalState.ca
We were funded by InnoCiteMTL.ca which is related to FounderFuel.com.  Just getting started, but great things coming!

**Comment by valdemar8080** [comment]
Hi, @Vanuan, @StephenOTT !  

It is very interesting. Let me introduce our project in more details.
The idea electronic public services was announced 03/02/2015 by Mr. Dmitry Dubilet as response to the society needs for more convenient and less corrupted public services while the authorities delayed. The team of enthusiasts was gathered and pushed first release in record time. The portal igov.org.ua launched 06/16/2015. As you see, it took three and a half months to convert the idea into practical realization on the first approach. Now the project involves several hundred volunteers and 50+ of them contribute daily.  

Total services q-ty – 518 (74 – already launched, 69 – coming soon) that include services for individuals and for business as well. The most popular services are – Registration of vehicles, Non-criminal record certificate, Income statement from a tax body, Apply for an international passport etc. The project is continuously expanding geographically but it depends on the willingness of regional authorities to be more innovative and less corrupted.

Now the project is 100% non-commercial and open-source. Donorship and grants are welcome of course. My opinion is the further logical steps are to internationalize and partially commercialize it. For example to encourage most active contributors and let them to work for foreign e-government paid projects. I think Dmitry Dubilet should be invited for discussion and express his meaning on that issue.

As we have well established team and the running product which fork I hope can be easily modified for needs of Canadian electronic government it’s a good idea to start operate internationally. The production team is located in Ukraine while BP architects who help authorities to sketch business processes for conversion into electronic form in Canada. And there may be direct contracts with Canadian authorities. In my opinion the easiest way to begin is to engage Canada-based company that work on e-government projects, has good relationship with authorities and outsource our Ukrainian experienced team. It not necessary should be a startup but existing software or BP consulting company. Although if you have a vision how to start that cooperation via startup procedure let us know. What is your meaning how our team can contribute to your e-govt projects? I see you develop your own e-govt product…

**Comment by StephenOTT** [comment]
@valdemar8080 very interesting that you were able to get so many volunteers!  Any details you can share about the culture or background of how and where these volunteers came from?

**Comment by valdemar8080** [comment]
To understand this phenomenon we should back to Feb. 2014 when the president of Ukraine Victor Yanukovich with his highly corrupted ruling ‘elite’ escaped from Ukraine. The revolution 2014 ended the corruption on the highest govt level but there were still many middle range officials who were continuing to extort bribes for any kind of certificates and other verification papers. So the right way to tackle the corruption was to convert public services in electronic form with minimal officials’ contacts with applicants and automatic time control for fulfilment.
Here is the inspiring post by Dmitry Dubilet (in Russian). You can translate it online.
https://www.facebook.com/dubilet/posts/10153169671823552
There was post-revolution crisis and Russian aggression on South-East of Ukraine. At the same time Ukraine enjoyed the flood of patriotism especially among well educated young people who did not want to have anything with old ‘regime’. Many volunteers appeared to help the army fight against Russian aggressors. They bought the equipment, uniform, food, medicines for their own money and delivered goods to the battle places on their own cars.   
The government had no money to digitalize services but volunteers appeared in IT area as well. 500+ people responded to Dmitry’s post and applied a registration form for IT-volunteership. Most of them were from Ukraine but some Ukrainians currently living abroad – software developers, UI-designers, QA from junior to senior level. Many of them were employed in IT companies even worldwide outsourcing giants like EPAM, Global Logic, Luxoft.

**Comment by valdemar8080** [comment]
@StephenOTT, see comment above, pls

**Comment by StephenOTT** [comment]
interesting
