### ISSUE TITLE
Реализовать поддержку автокомплита для справочников Currency

### ISSUE THREAD

**Issue by OlgaTurenko** [e-government-ua/i#969]
По примеру (не полностью) задачи #584 - реализовать аналогичную поддержку автокомплита.
С обязательной поддержкой параллельного одновременного наличия нескольких таких полей в одной форме (хоть и с разными суффиксами).

- для сущности Currency (#966)

- id полей: sCurrency, sCurrency_1, sCurrency_2 и т.д. (sCurrency*)

- если в форме встречается поле c id, начинающимся с sCurrency_123, то отрисовывать вместо него автокомплит с соответствующим контентом, при выборе элемента из которого - сохранять его sID_UA в поле c id=sID_UA_Currency_123

**Comment by hordesalik** [comment]
Тестовый БП есть?

**Comment by GrekD** [comment]
@hordesalik 
тестовый бп:
https://test.igov.org.ua/service/60/general

поля:
*Валюта контракту:
*Валюта розрахунку:

логин-пароль для дашборда: test_eds

**Comment by hordesalik** [comment]
Готово. Проверил в дашборде - все пришло. Можно тестировать

**Comment by nazarenkod** [comment]
Автокомплит работает для полей:
*Валюта контракту:
*Валюта розрахунку:

**Comment by GrekD** [comment]
коллеги, добрый день
у меня не получается теперь подать заявку пишет вот что (это вверху на красной полосе)
помилкаthis.value is null (caused by "undefined")

в файрбаге нет "красных" ошибок
на последнем действии где я нажала "подать заявку" во вкладке "сеть-ответ" вобще пусто
но заявка не подается
почему я у Вас спрашиваю - потому что после того как я переделывала процесс для проверки  этого ишью
я больше его не трогала
думаю, может это из-за доработок что-то?
